### ISSUE TITLE
UI ToDo list

### ISSUE THREAD

**Issue by amdomanska** [CottageLabs/jct#1]
- [x] Turn off cache for autocomplete boxes/generally make sure they give sensible results
- [x] Reduce the space taken by the autocomplete box - either limit the results to the top 10, or make it fixed height and scrollable
- [x] Add "Not in HE" checkbox to the Institution search
- [x] Add the "Explain this Result" section
- [x] Normalise the result boxes as we discussed
- [x] Add the "Journal Checker Tool" header in the top right
- [x] Add the help modals for each result box
- [x] Add the "print this result" button
- [x] Add a "beta" label somewhere
